apiVersion: v1
kind: Service
metadata:
  name: {{ include "third-places.fullname" . }}-postgresql
  labels:
    {{- include "third-places.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    {{- include "third-places.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  type: {{ .Values.postgresql.serviceType }}
  ports:
    - name: postgresql
      port: 5432
      nodePort: 30432
