# Generated by Django 4.2 on 2023-05-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='locations',
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='api.tag'),
        ),
        migrations.RemoveField(
            model_name='location',
            name='hours',
        ),
        migrations.AddField(
            model_name='location',
            name='hours',
            field=models.ManyToManyField(blank=True, related_name='locations', to='api.businesshours'),
        ),
    ]
