# Generated by Django 4.2 on 2023-05-09 20:17

import requests
from os import environ

from django.contrib.gis.geos import Point
from django.db import migrations
from django.utils import timezone


def populate_locations(apps, schema_editor):
    Location = apps.get_model('api', 'Location')
    LocationType = apps.get_model('api', 'LocationType')

    YELP_URL = 'https://api.yelp.com/v3/businesses/search' \
        + '?location=Philadelphia' \
        + '&latitude=39.952584' \
        + '&longitude=-75.165222' \
        + '&categories=cafes' \
        + '&limit=50'

    yelp_result = requests.get(
        YELP_URL,
        headers={'Authorization': f'Bearer {environ.get("YELP_API_KEY")}'},
        timeout=5
    )

    businesses = yelp_result.json()['businesses']

    default_location_type = LocationType(
        code='default',
        name='Default Location'
    )
    default_location_type.save()

    for b in businesses:
        location = Location(
            name=b['name'],
            address=' '.join(b['location']['display_address']),
            location=Point(
                b['coordinates']['longitude'],
                b['coordinates']['latitude']
            ),
            location_type=default_location_type,
            price_category=b.get('price', ''),
            created_datetime=timezone.now(),
            modified_datetime=timezone.now()
        )
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adjust_biz_hours_and_location_relation'),
    ]

    operations = [
        migrations.RunPython(populate_locations, migrations.RunPython.noop)
    ]
